### PR TITLE
Somoclu parallel working version

### LINKED ISSUE #317: Implement parallel execution for somoclu
Adding a parallel capable version for somoclu

### PR DESCRIPTION
**Pull request by joselotl**
I put the analysis of the photometric data in an iterator to allow it to work in parallel.

### CODE REVIEW

**Comment by joselotl** [comment]
I have finally fixed the bug that made the unit tests fail. I was initiallizing one of the histograms with np.empty instead of np.zero and some of the inicial values would modify the final results.
Now the somoclu summarizer is working in parallel

**Comment by joselotl** [comment]
@yanzastro @eacharles If you would approve this PR, it is ready to merge.

**Review by eacharles — CHANGES_REQUESTED** [review]
Could you rebase or merge to the head of the main branch and check the somoclu demo notebook to make sure you aren't overwriting new changes there.

**Comment by joselotl** [comment]
@eacharles I fixed the changes in the notebooks that were been reverted by my commits and also fixed another conflict with the  new input_iterator.
I think it is ready to merge

**Review by eacharles — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
