### PR TITLE
Speed up Inform_BPZ_lite stage

### PR DESCRIPTION
**Pull request by joezuntz**
This adds a simple parallelization to the slow part of the `Inform_BPZ_lite` stage, which is the fitting of the n(z) parameters. The function parallelizes very simply, since the log-like is just a sum over values from each spec-z galaxy.

Every ceci stage automatically has `rank` and `size` attributes which come from MPI.

### CODE REVIEW

**Comment by joezuntz** [comment]
Don't review yet not ready!

**Comment by joezuntz** [comment]
This is ready for review now. The code coverage seems to be a false alarm - it's not a file related to this PR.

**Review by eacharles — COMMENTED** [review]
Generally looks fine to me.   I'm not sure I understand why some of the changes got included in the diff.   Perhaps the way we did the merging?

**Review by sschmidt23 — APPROVED** [review]
Looks good, code is a factor of >20 faster now

**Pull request merged**
