### PR TITLE
Issue/87/fileio

### LINKED ISSUE #87: switch IO to using the tables_io package.
Basically I think we should remove the fileIO.py file and move that functionality to some combination of the tables_io and qp packages.

Anything with `qp` in the name should probably go to qp.

Places that we need to change.  

rail/estimation/estimator.py
tests/test_algos.py:from rail.fileIO import iter_chunk_hdf5_data, load_training_data
tests/test_estimator.py:from rail.fileIO import write_output_file
tests/test_fileIO.py:from rail.fileIO import load_training_data, initialize_qp_output
examples/estimation/RAIL_estimation_demo.ipynb:    "from rail.fileIO import *" 
examples/estimation/main.py:from rail.fileIO import load_training_data
examples/estimation/main.py:from rail.fileIO import initialize_writeout, iter_chunk_hdf5_data
examples/estimation/main.py:from rail.fileIO import write_out_chunk, finalize_writeout
examples/estimation/main.py:from rail.fileIO import write_qp_output_chunk, initialize_qp_output
examples/estimation/main.py:from rail.fileIO import qp_reformat_output

### LINKED ISSUE #98: chunked writing of qp files
The examples/estimation/main.py file has calls to a couple of temporary functions that were in rail/fileIO.py which have been removed (they were kludgey and bad anyway, and were always meant to be placeholder until the functionality was properly incorporated into qp).  We need to update a couple lines in main.py once the new functions exist in qp.

### PR DESCRIPTION
**Pull request by sschmidt23**
This PR addresses #87 to remove rail/fileIO.py functions and switch to using `tables_io`.  This is pretty straightforward, except that the rail/estimation/main.py file uses three "temporary" functions to write a chunked hdf5 file in qp format.  This is being handled in a separate issue on `qp` that is not quite finished yet.  So, this PR will temporarily break main.py run in one mode, but that will be fixed in a few days, so I think we're fine to proceed and I'll create a separate issue reminding myself to fix main.py next week after the qp PR is merged in.

### CODE REVIEW

**Comment by sschmidt23** [comment]
Thanks to some help from @eacharles we now have all fileIO functionality needed within qp, and all functions have been moved out of rail/fileIO.  I think that this is now ready to go.

**Review by eacharles — COMMENTED** [review]
Do we need to include qp and tables_io here?

**Comment by sschmidt23** [comment]
@eacharles are you referring to docs/requirements.txt when you ask about including?  If so, then yes, I think they do belong, I will add in a second. I forgot to create a separate issue for creating an automated update of docs/requirements.txt, will do that now as well.

**Comment by eacharles** [comment]
Also setup.py if there is such a thing.

**Comment by sschmidt23** [comment]
I added tables-io to setup.py and tables-io and qp to the docs/requirements.txt.  As mentioned in an earlier comment, I'll try setting up a GitHub action to automatically generate a requirements.txt from the setup.py in a separate issue.

**Review by eacharles — APPROVED** [review]

**Pull request merged**
