### PR TITLE
Issue/157/io nb

### LINKED ISSUE #157: Add improved notebook demonstrating fileIO, tables_io, and the DataStore
This is still a little confusing, and an additional notebook will be instructive for users.

### PR DESCRIPTION
**Pull request by sschmidt23**
Adding another demo notebook (not sure if examples/core is the correct location for this, thoughts?) with some extra explanation for tables_io, the rail.core.DataStore, and fileIO that will hopefully clarify usage for people just getting started.

@joselotl you mentioned some confusion about fileIO, are we missing anything in this demo that you had questions about?  Can you successfully run this notebook?  Same question for @aimalz and @eacharles, anything we should add/rephrase here?  Should we move to goldenspike directory for better visibility?

### CODE REVIEW

**Review by eacharles — APPROVED** [review]
I ran the notebook and it is very helpful, thanks Sam!

**Comment by sschmidt23** [comment]
I'm going to merge this in, @joselotl or @aimalz if you have further comments on improving the notebook we can open a new issue/PR to fix it up further.

**Comment by joselotl** [comment]
I'm having problems executing the second to last cell:
newens = qp.read("KNNPZ_estimates.hdf5")

The error is
~/local/anaconda3/envs/pz/lib/python3.9/site-packages/qp-0.5.2.dev1+g8f6c2c4-py3.9.egg/qp/factory.py in read(self, filename)
    154         data = self._build_data_dict(md_table, data_table)
    155 
--> 156         pdf_name = data.pop('pdf_name')
    157         pdf_version = data.pop('pdf_version')
    158         if pdf_name not in self: #pragma: no cover

KeyError: 'pdf_name'

I wonder if it has something to do with the qp version? @sschmidt23

**Comment by sschmidt23** [comment]
Have you grabbed a fresh copy of `qp` within the last few days?  Eric just patched a bug in the writing out hdf5 files that causes this error, so if you grab the latest qp this error should go away.

**Comment by joselotl** [comment]
Thank you, it solved my problem

**Pull request merged**
