### PR TITLE
Let users of the NN and flexzboost select which bands to use

### PR DESCRIPTION
**Pull request by joezuntz**
This makes it possible to use a subset of bands with two of the estimators.

### CODE REVIEW

**Comment by sschmidt23** [comment]
This looks fine, I added `bands` as defaults in the two examples as well just for completeness.  At some point soon I need to add in a more flexible naming convention for bands, which are currently hardcoded, but that should not conflict with this functionality.

I'll also note that for BPZ_lite, you can control which bands are used via the `columns` file, e.g. in `configs/test_bpz.columns` file you can comment out lines beginning with particular filters to stop DESC_BPZ from using them in the analysis.

But yes, go ahead and merge this in.

**Comment by johannct** [comment]
Is there a unit test to check the syntax of `bands`? Is it "gri" or "g,r,i" or what?

**Review by sschmidt23 — APPROVED** [review]

**Comment by joezuntz** [comment]
I have added a test for what @johannct mentioned above - you now get an error message for non-letter bands.  And there is a unit test to make sure these are correctly raised.

**Comment by joezuntz** [comment]
Thanks all. Malz says I can merge :-)

**Pull request merged**
