### PR TITLE
Create GPz_classifier.py

### PR DESCRIPTION
**Pull request by pwhatfield**
Currently just a copy of randomPZ

### CODE REVIEW

**Comment by pwhatfield** [comment]
No need to merge, just initialising...

**Comment by johannct** [comment]
You may want to call it GPz perhaps

**Comment by aimalz** [comment]
Perhaps this distinguishes it from the regressor variant? (Also, we can always fiddle with naming consistency later on.)

**Comment by pwhatfield** [comment]
Yes, sorry that is slightly confusing calling it classifier, have just changed to GPz.py for the moment...

**Comment by eacharles** [comment]
This has been pretty overtaken by events.  It was just a placeholder, so I'm going to close this issue.

**Pull request closed without merging**
